
= Hero Microservice

==== Bootstrapping the Hero REST Endpoint
```
mkdir -p shikanga-quarkus-super-heroes-workshop/shikanga-super-heroes/rest-hero

cd shikanga-quarkus-super-heroes-workshop/shikanga-super-heroes/rest-hero

mvn io.quarkus:quarkus-maven-plugin:1.0.1.Final:create \
    -DprojectGroupId=uk.co.shikanga.workshop.super-heroes \
    -DprojectArtifactId=rest-hero \
    -DprojectVersion=1.0-SNAPSHOT \
    -DclassName="uk.co.shikanga.workshop.superheroes.hero.HeroResource" \
    -Dpath="api/heroes"
    
```
==== Running the Application
When ready to run our application. Use:
```
./mvnw compile quarkus:dev:
```
Then check that the endpoint returns hello as expected:
```
$ curl http://localhost:8080/api/heroes
hello
```

==== Development Mode
*quarkus:dev* runs Quarkus in development mode. This enables hot deployment with background compilation, which means that when you modify your Java files and/or your resource files and invoke a REST endpoint (i.e. cUrl command or refresh your browser), these changes will automatically take effect. This works too for resource files like the configuration property and HTML files. Refreshing the browser triggers a scan of the workspace, and if any changes are detected, the Java files are recompiled and the application is redeployed; your request is then serviced by the redeployed application. If there are any issues with compilation or deployment an error page will let you know.

The development mode also allows debugging and listens for a debugger on port 5005. If you want to wait for the debugger to attach before running you can pass *-Dsuspend=true* on the command line. If you don’t want the debugger at all you can use *-Ddebug=false.*

==== Testing the Application
In the generated pom.xml file, you can see 2 test dependencies:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-junit5</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <scope>test</scope>
</dependency>
```
Quarkus supports Junit 4 and Junit 5 tests. In the generated project, we use Junit 5. Because of this, the version of the Surefire Maven Plugin must be set, as the default version does not support Junit 5.
```
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.0.1.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.0.1.Final</quarkus.platform.version>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
  </properties>
```
We also set the *java.util.logging* system property to make sure tests will use the correct log manager.
```
<plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemProperties>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
          </systemProperties>
        </configuration>
      </plugin>
```
Execute tests with the following command:
```
./mvnw test
```
==== Packaging and Running the Application
The application is packaged using
```
./mvnw package
```
It produces 2 jar files in */target:*

* *rest-hero-1.0-SNAPSHOT.jar* : containing just the classes and resources of the projects, it’s the regular artifact produced by the Maven build;

* *rest-hero-1.0-SNAPSHOT-runner.jar* : being an executable jar. Be aware that it’s not an über-jar as the dependencies are copied into the *target/lib* directory.

You can run the application using:
```
java -jar target/rest-hero-1.0-SNAPSHOT-runner.jar
```

==== Transactions and ORM
The Hero API’s role is to allow CRUD operations on Super Heroes. In this module we will create a Hero entity and persist/update/delete/retrieve it from a Postgres database in a transactional way.

===== Installing the PostgreSQL Dependency
To install the PostgreSQL driver dependency, just run the following command:
```
$ ./mvnw quarkus:add-extension -Dextensions="jdbc-postgresql"
```
This will add the following dependency in the pom.xml file:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
```